Add new function: skip vlan, scan vlan, and scan trunk port
Cacti/plugin_mactrack pull request #221
Opened 2024-06-12 03:36 UTC by xxconn

Add new function:

In site, add skip vlan, and scan vlan

In device, add scan-trunk-port for VM.

2024-06-12 10:12 UTC, TheWitness requested changes
Generally column additions require a version increase.  Just increment the point release in the information file.

2024-06-12 10:12 UTC, TheWitness commented on setup.php
> +		'description' => 'VLAN ID always forced to be skipped scanning',
Should indicate is column separated or space in descriptions.  I think in MakTrack, it's generally comma. Double check though.

2024-06-12 10:12 UTC, TheWitness commented on setup.php
> +		'description' => 'Some VMware network port will be configured with 802.1Q',
Same comment here.  You could say something like "A comma delimited is of ..."

2024-06-12 10:12 UTC, TheWitness commented on setup.php
> +		'description' => 'VLAN ID to be scaned',
Ditto on previous two comments.

2024-06-12 11:23 UTC, xxconn commented on setup.php
> +		'description' => 'VLAN ID to be scaned',
Modified the new field's description.

2024-06-12 11:36 UTC, xxconn commented
I will modify INFO and add new fields to database.php tomorrow.

2024-06-13 02:04 UTC, xxconn commented
Modified database.php and INFO.

2024-06-13 03:53 UTC, TheWitness approved these changes

2024-06-13 03:53 UTC, merged